upload: Fix a critical and stupid bug

diff --git a/libexec/relax-upload b/libexec/relax-upload
--- a/libexec/relax-upload
+++ b/libexec/relax-upload
@@ -95,7 +95,7 @@ while [ $# -ne 0 ];  do
 			service=$arg
 		else
 			ipa_file=$arg
-			[[ ! -f "$ipa_file" ]] || die "Not found $ipa_file"
+			[[ -f "$ipa_file" ]] || die "Not found $ipa_file"
 		fi
 		;;
 	esac
