Support Travis CI
- Add Build Status image in README
- Add certificates and mobileprovision for Travis CI
- Add sample dir
- Add const file
- Distinguish a codesign identitiy between Distribution and Developer
- Add new commands
    - enc/dec/rm
- Add util-keychain file
- Enhance 'add' command
    - Ensure a provisioning profile directory existance
    - Add indeitity validation
    - Set up key partition list on macOS Sierra
    - Get rid of a unknown security error
        `security cms -D` will print this error in macOS Sierra
         security: SecPolicySetValue: One or more parameters passed to a function
         were not valid.
         But decoding mobileprovision is success.
- bugfix
    - test: Fix resign tests
    - test: Fix package bats
    - test: Fix parse_config.bats

diff --git a/libexec/relax-add b/libexec/relax-add
--- a/libexec/relax-add
+++ b/libexec/relax-add
@@ -3,52 +3,73 @@
 
 usage_add () {
 	cat <<-EOM
-	usage: ${ME} add [option] <provisioning-profile>
-	options:
-	    -f	A provisioning profile will be force added.
+	usage: ${ME} add <provisioning-profile>
+	       ${ME} add -P <password> <p12>
+
 	EOM
 }
 
-# add_provisioning_profile [-f]  <provisioning-profile>
-add_provisioning_profile () {
-
-	local is_force=false
+# add_identities  -P <password> <p12>
+add_identities () {
+	local password=
 	while [ $# -ne 1 ];
 	do
+		if [ $# = 0 ]; then
+			usage_add
+			fin
+		fi
+
 		arg=$1
 		shift
 		case $arg in
-		-f)
-			is_force=true
+		-P)
+			password=$1
+			shift
 			;;
 		esac
 	done
 	
+	if ! is_exist_keychain $REL_KEYCHAIN; then
+		logi "$ARROW Creating relax.keychain"
+		create_relax_keychain
+	fi
+
+
+	logi "$ARROW Importing PKCS12: $1"
+	import_p12_into_keychain -k $REL_KEYCHAIN_PASSWD -P $password $1 $REL_KEYCHAIN
+
+	init_keychain -k $REL_KEYCHAIN_PASSWD $REL_KEYCHAIN 
+	logi "Default keychain: $($SECURITY default-keychain | xargs)"
+
+	logi "$ARROW Validating imported certificates..."
+	validate_certs -P $password $1
+}
+
+# add_provisioning_profile [-f]  <provisioning-profile>
+add_provisioning_profile () {
 	local provisioning_file="$1"
 
 	if ! [ -z $provisioning_file ] && ! [ -f $provisioning_file ]; then
 		die "Not found $provisioning_file "
 	fi
 
+	local temp_provisioning_plist="$REL_TEMP_DIR/provisioning.plist"
 
-	if ! $is_force; then
-		local temp_provisioning_plist="$REL_TEMP_DIR/provisioning.plist"
+	decode_mobileprovision "$provisioning_file" "$temp_provisioning_plist"
 
-		security cms -D -i "$provisioning_file" > $temp_provisioning_plist
+	provisioning_uuid=$(/usr/libexec/PlistBuddy -c "Print :UUID" $temp_provisioning_plist)
+	provisioning_name=$(/usr/libexec/PlistBuddy -c "Print :Name" $temp_provisioning_plist)
 
-		provisioning_uuid=$(/usr/libexec/PlistBuddy -c "Print :UUID" $temp_provisioning_plist)
-		provisioning_name=$(/usr/libexec/PlistBuddy -c "Print :Name" $temp_provisioning_plist)
-
-		local stored_provisionig_file="$PROVISIONING_DST_DIR/$provisioning_uuid.mobileprovision" 
-		if [ -f "$stored_provisionig_file" ]; then
-			logi "Already existing. Use -f option if you still encounter a codesign problem."
-			fin
-		fi
+	mkdir -p "$PROVISIONING_DST_DIR"
+	local stored_provisionig_file="$PROVISIONING_DST_DIR/$provisioning_uuid.mobileprovision" 
+	if [ -f "$stored_provisionig_file" ]; then
+		logi "Already existing"
+		fin
 	fi
 
 	logi "$ARROW Installing Provisioning profile: $provisioning_file"
 	cp "$provisioning_file" "$stored_provisionig_file"
-	logi "Done."
+	logi "Added: $stored_provisionig_file"
 }
 
 if test $# = 0; then
@@ -63,7 +84,18 @@ case $1 in
 	;;
 esac
 
-add_provisioning_profile "$@"
+if [[ -f "$1" ]]; then
+	if grep -q "Provisioning Profile" "$1"; then
+		add_provisioning_profile "$@"
+	else
+		usage_add
+		fin
+	fi
+elif [[ $1 == "-P" ]]; then
+	add_identities "$@"
+else
+	die "Not Found $1"
+fi
 
 if test $? = 0; then
 	logi "${GREEN}Success${NC}"
diff --git a/libexec/util b/libexec/util
--- a/libexec/util
+++ b/libexec/util
@@ -78,11 +78,28 @@ progress_bar()
 	fi
 }
 
+compare_versions()
+{
+    local v1=( $(echo "$1" | tr '.' ' ') )
+    local v2=( $(echo "$2" | tr '.' ' ') )
+    local v1len="${#v1[*]}"
+    local v2len="${#v2[*]}"
+    local len="$(( $v1len > $v2len ? $v1len : $v2len ))"
+    for ((i=0; i<len; i++))
+    do
+        [ "${v1[i]:-0}" -gt "${v2[i]:-0}" ] && echo -n 1 && return 0
+        [ "${v1[i]:-0}" -lt "${v2[i]:-0}" ] && echo -n -1 && return 0
+    done
+    echo -n 0
+    return 0
+}
+
 check_toolchain () {
 	which xcodebuild > /dev/null || die "Not found xcodebuild"
 	which /usr/libexec/PlistBuddy > /dev/null || die "Not found /usr/libexec/PlistBuddy"
 	which plutil > /dev/null || die "Not found plutil"
 	which codesign > /dev/null || die "Not found codesign"
+	which security > /dev/null || die "Not found security"
 }
 
 pop_all() {
@@ -141,6 +158,7 @@ fin () {
 
 die () {
 	die_with_status 1 "$@"
+
 }
 
 die_with_status () {
@@ -190,7 +208,7 @@ logi () {
 }
 
 declare -x -f print_progress_time progress_bar
-declare -x -f check_toolchain 
+declare -x -f check_toolchain compare_versions 
 declare -x -f fin die die_with_status
 declare -x -f logi logv logd __log
 declare -x -f make_temp pop_all clean_temp TRAP
