Fix bugs
- Fix handling path and scheme including spaces
- Fix unbound PRODUCT_BUNDLE_IDENTIFIER
- Add 'REL_' prefix to LOG_LEVEL
- Change file modes of non command files
- Fix errors with a workspace build
- Relfile: Update Relfile spec file
- util: Add check_toolchain()
- validate: Show Info.plist in a product
- validate: Fix bundle id duplicate check proccess
- export: Deprecate '--latest' option
- test: Add comments in Relfile of SampleApp
- Improve xcodebuild param handling
- Improve YAML parser a bit
- Fix relax-upload
- util-config: Print a warning if a log formatter isn't installed
- Fix config_collect_releases()
- Fix a syntax issue at _export_config() if 'awk' isn't GNU version

diff --git a/libexec/relax-export b/libexec/relax-export
--- a/libexec/relax-export
+++ b/libexec/relax-export
@@ -4,9 +4,10 @@
 
 usage_export () {
 	cat <<-EOM
-	usage: ${ME} export <release> <archive-path>|--latest
-	options:
-	    --latest		: Use the latest archive file instead of a archive path
+	usage: ${ME} export <release> [<archive-path>]
+
+	If you don't specify an archive, it will export the last one of
+	a release type.
 	EOM
 }
 
@@ -68,14 +69,17 @@ export_generate_optoin_list() {
 }
 
 export_archive () {
-	local archive_path=$1
-	shift
+	if [[ $# != 1 ]]; then
+		die "export_archive: bad argument"
+	fi
 
+	logi "$ARROW Exporting $1"
+
+	local export_path="${1%/*}"
 	local export_option_plist=$EXPORT_OPTIONS_PLIST
-	local export_path=$(dirname $archive_path)
 
-	cp -a $archive_path $REL_TEMP_DIR/xcarchive
-	local archive_path=$REL_TEMP_DIR/xcarchive
+	local archive_path="$REL_TEMP_DIR/xcarchive"
+	cp -a "$1" "$archive_path"
 
 	export_generate_optoin_list
 	
@@ -99,45 +103,47 @@ export_archive () {
 	fi
 
 	if test -d "$archive_path/dSYMs"; then
-		logi "$ARROW Export dSYMs"
+		logi "$ARROW Fetching dSYMs"
 	
-		local dsym_file=$export_path/"$PROJECT_NAME".dSYMs.zip
-		ditto -c -k --sequesterRsrc --keepParent "$archive_path/dSYMs" $dsym_file
+		local dsym_file="$export_path/$PRODUCT_NAME.dSYMs.zip"
+		ditto -c -k --sequesterRsrc --keepParent "$archive_path/dSYMs" "$dsym_file"
 
-		logi "Exported dSYMs.zip: $dsym_file"
+		logi "dSYMs.zip: $dsym_file"
 	fi
 
-	logi "$ARROW Export IPA"
+	logi "$ARROW Creating IPA"
 
-	if [ -f "$export_path/$PROJECT_NAME.ipa" ]; then 
+	if [ -f "$export_path/$PRODUCT_NAME.ipa" ]; then 
 		logi "Found the same IPA file so it is removed."
-		rm -rf "$export_path/$PROJECT_NAME.ipa"
+		rm -rf "$export_path/$PRODUCT_NAME.ipa"
 	fi
 
-	params=(-exportArchive -archivePath "$archive_path" -exportPath "$export_path")
-	params=(${params[@]} -exportOptionsPlist "$export_option_plist")
+	local params=()
+	params+=(-exportArchive -archivePath "$archive_path" -exportPath "$export_path")
+	params+=(-exportOptionsPlist "$export_option_plist")
 
 	### Deprecated
-	#	params=(${params[@]} -exportFormat ipa)
-	#	params=(${params[@]} -exportProvisioningProfile "$provisioning_name")
+	#params=(-exportFormat ipa)
+	#params+=(-exportProvisioningProfile "$provisioning_name")
 
 	logfile="$export_path/export.log"
-	logi "Run: \`xcodebuild ${params[@]}\`"
-	logi "Log: $logfile"
+	logi "Run: xcodebuild ${params[@]}"
+	logi "Log: ${logfile}"
 
-	if [[ "${LOG_LEVEL:-undefined}" =~ .*"$LOG_LEVEL_VERBOSE".* ]]; then
-		xcodebuild "${params[@]}" 2>&1 | tee $logfile; test ${PIPESTATUS[0]} -eq 0 || return 1
+	if [[ "${REL_LOG_LEVEL:-undefined}" =~ .*"$REL_LOG_LEVEL_VERBOSE".* ]]; then
+		xcodebuild "${params[@]}" 2>&1 | tee "${logfile}"; test ${PIPESTATUS[0]} -eq 0 || return 1
 	else
-		xcodebuild "${params[@]}" > $logfile 2>&1 || return 1
+		xcodebuild "${params[@]}" > "${logfile}" 2>&1 || return 1
 	fi
 
 	# update a symbolic link of the latest archive
-	if [[ ! -n $(find $export_path -name "*.ipa") ]]; then
+	find "$export_path" -name "*.ipa"
+	if [[ ! -n $(find "$export_path" -name "*.ipa") ]]; then
 		die "Not found IPA file in $export_path"
 	fi
 
-	local ipa_path=$(find $export_path -maxdepth 1 -mindepth 1 -name "*.ipa" | head -1)
-	logi "Exported IPA: $ipa_path"
+	local ipa_path=$(find "$export_path" -maxdepth 1 -mindepth 1 -name "*.ipa" | head -1)
+	logi "IPA: $ipa_path"
 
 	rm -f "$LATEST_IPA"
 	ln -fs "$ipa_path" "$LATEST_IPA"
@@ -172,20 +178,14 @@ do
 		fin
 		;;
 	--complete)
-		prev=$1
-		shift
-		comp="--latest"
-		if ! [[ $comp =~ $prev ]]; then
-			echo "$comp"
-		fi
 		fin
-		;;
-	--latest)
-		target_archive_file="$(relax-show $release archive)"
 		;;
 	*)
 		if [[ $arg =~ (.).xcarchive ]]; then
 			target_archive_file="$arg"
+			if [[ ! -d $target_archive_file ]]; then
+				die "Not found $target_archive_file "
+			fi
 		else
 			release=$arg
 		fi
@@ -198,22 +198,16 @@ if test ${release:-undefined} = undefined; then
 	fin
 fi
 
+if [[ -z "$target_archive_file" ]]; then
+	target_archive_file="$(relax-show $release archive)"
+	if [[ ! -d $target_archive_file ]]; then
+		die "Not found the last archive. Please archive '$release'"
+	fi
+fi
+
+
 trap 'teardown_build' EXIT INT TERM
 setup_build $release
 prepare_export
 
-if test -z "$target_archive_file"; then
-	die "Please build an archive file for $release."
-fi
-
-if test $# = 1;
-then
-	export_archive "$@"
-else
-	if test -z $target_archive_file; then
-		usage_export
-		fin
-	else
-		export_archive "$target_archive_file"
-	fi
-fi
+export_archive "$target_archive_file"
diff --git a/libexec/relax-validate b/libexec/relax-validate
--- a/libexec/relax-validate
+++ b/libexec/relax-validate
@@ -18,7 +18,7 @@ prepare_validate () {
 
 
 validate_app () {
-	local app_path=$1
+	local app_path="$1"
 
 	local success=false
 	if test ! -d "${app_path}"; then
@@ -32,10 +32,12 @@ validate_app () {
 	fi
 	logi "$ARROW Validating $product_name..."
 
-	logi "$ARROW Verifying code signing"
+	logi "$ARROW Check CodeSigning"
 
+	logv "$ARROW Verifying $app_name"
 	codesign -dv "${app_path}" 2>&1 | grep -e "Format\|Identifier\|Signed Time" | tee $REL_TEMP_DIR/codesign_info
-	if codesign --verify --no-strict -vvvv "${app_path}" 2>&1 | logv; test ${PIPESTATUS[1]} -eq 0; then
+	codesign --verify --no-strict -vvvv "${app_path}" 2>&1 | logv;
+	if [[ $? = 0 ]]; then
 		success=true
 	else
 		success=false
@@ -47,10 +49,13 @@ validate_app () {
 	# Check Framework codesignning
 	if [[ -d ${app_path}/Frameworks ]]; then
 		local fm_name fm_team_id fm_temp_codesign_info
-		for framework in $(find "${app_path}/Frameworks" -name "*" -maxdepth 1 -mindepth 1); do
-			fm_name=${framework##*/}
+		find "${app_path}/Frameworks" -name "*" -maxdepth 1 -mindepth 1 2>/dev/null |\
+		while IFS= read framework
+		do
+			fm_name="${framework##*/}"
 
-			if codesign --verify --no-strict -vvvv "${app_path}" 2>&1 | logv; test ${PIPESTATUS[1]} -eq 0; then
+			logv "$ARROW Verifying $fm_name"
+			if codesign --verify --no-strict -vvvv "${framework}" 2>&1 | logv; test ${PIPESTATUS[1]} -eq 0; then
 				success=true
 			else
 				success=false
@@ -70,13 +75,13 @@ validate_app () {
 				success=false
 			fi
 		done
-		logi "$ARROW All Embedded Frameworks matched \"$cs_team_id\"."
+		logi "All Embedded Frameworks matched \"$cs_team_id\"."
 	fi
 
 	if [[ $success != true ]]; then
 		die "Failed codesign verification."
 	fi
-	
+
 	logi "$ARROW Checking Entitlements and Provisioning"
 
 	# Show entitlement
@@ -92,7 +97,6 @@ validate_app () {
 	logi "$ARROW Embedded provisioning profile"
 	local mobileprovision=$REL_TEMP_DIR/embedded.mobileprovision
 	security cms -D -i "${app_path}/embedded.mobileprovision" > $mobileprovision
-	cat $mobileprovision | awk '{ print $0 }' | logv  # Pass `awk' to append a newline before EOF.
 	local mp_name=$(/usr/libexec/PlistBuddy -c "Print :Name" $mobileprovision)
 	local mp_uuid=$(/usr/libexec/PlistBuddy -c "Print :UUID" $mobileprovision)
 	local mp_team=$(/usr/libexec/PlistBuddy -c "Print :TeamName" $mobileprovision)
@@ -106,6 +110,26 @@ validate_app () {
 	Creation Date: $mp_cdate
 	Expiration Date: $mp_edate
 	EOM
+	cat $mobileprovision | awk '{ print $0 }' | logv  # Pass `awk' to append a newline before EOF.
+
+	# Show Info.plist
+	logi "$ARROW Show Info.plist"
+	local info_plist_path info_version info_bundle_version info_bundle_identifier
+	info_plist_path="$REL_TEMP_DIR/Info.plist"
+	plutil -convert xml1 "${app_path}/Info.plist" -o "$info_plist_path"
+	info_version=$(print_info_plist version "$info_plist_path")
+	info_bundle_version=$(print_info_plist bundle_version "$info_plist_path")
+	info_bundle_identifier=$(print_info_plist bundle_identifier "$info_plist_path")
+	cat <<-EOM | logi
+	Version: ${info_version}(${info_bundle_version})
+	Bundle Identifier: ${info_bundle_identifier}
+	EOM
+	cat "${info_plist_path}" | logv
+	
+	if ! [[ $cs_app_id =~ $info_bundle_identifier ]]; then
+		success=false
+		logi "Not match CodeSigining and Info.plist bundle identifier"
+	fi
 
 	# Check if archived-expanded-entitlements.xcent matches the signed entitlements
 	if [[ $app_path =~ xcarchive ]]; then
@@ -122,20 +146,25 @@ validate_app () {
 		fi
 	fi
 
-	logi "$ARROW Check bundle identifier duplicates in ${app_path##*/}"
-	for i in $(find $app_path -name Info.plist); do
+	logi "$ARROW Check duplicates of all bundle identifiers in ${app_path##*/}"
+	find "$app_path" -name "Info.plist" -mindepth 2 |\
+	while IFS= read info
+	do
 		local new_id bundle_ids bundle_path app_name
-		if /usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" $i 2>&1 | grep -qv "Does Not Exist"; then
-			new_id="$(/usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" $i)"
-			bundle_path=${i##$app_path}
+		local bundle_info_plist_path="$REL_TEMP_DIR/Info.plist"
+		plutil -convert xml1 "$info" -o "$bundle_info_plist_path"
+		logd "$bundle_info_plist_path"
+		new_id="$(print_info_plist bundle_identifier "$bundle_info_plist_path")"
+		if [[ -n $new_id ]]; then
+			bundle_path=${info##$app_path}
 			app_name=${app_path##*/}
-			logv "${app_name}${bundle_path%/*}: $new_id (${app_name}${bundle_path})" 
+			logi "${app_name}${bundle_path}: $new_id"
 			if [[ $bundle_ids =~ $new_id ]]; then
-				is_success=false
-				logi "$ERR A duplicated bundle identifier($new_id) is found in $i"
+				success=false
+				logi "$ERR A duplicated bundle identifier($new_id) is found in $info"
 			fi
-			bundle_ids+="$new_id"
 		fi
+		bundle_ids+="$new_id"
 	done
 
 	# Check match codesign Team Identifier and a Team ID for the entitlements and the provisioning profile
@@ -158,20 +187,20 @@ validate_product () {
 	fi
 
 	local product_path="${1%/}"
-	local app_paths
+	local app_path
 	if [[ "$product_path" =~ .*\.app  ]]; then
 		logd "app: $product_path"
 
 		[[ -d $product_path ]] ||  die "Not found $product_path"
 
-		app_paths=( "$1" )
+		app_path="$1"
 
 	elif [[ "$product_path" =~ (.*)\.xcarchive  ]]; then
 		logd "archive: $product_path"
 
 		[[ -d $product_path ]] ||  die "Not found $product_path"
 
-		app_paths=( $(find "$1" -name *.app) )
+		app_path="$(find "$1" -name *.app)"
 
 	elif [[ "$product_path" =~ (.*)\.ipa ]]; then
 		logd "ipa: $product_path"
@@ -179,15 +208,15 @@ validate_product () {
 		[[ -f $product_path ]] || die "Not found $1"
 
 		unzip -q "$1" -d $REL_TEMP_DIR
-		app_paths=( $(find "$REL_TEMP_DIR/Payload" -name *.app) )
+		app_path="$(find "$REL_TEMP_DIR/Payload" -name *.app)"
 	else
 		die "Not found $1"
 	fi
 
-	if [[ ${#app_paths[@]} != 1 ]]; then
-		die "Found multiple .app directories: ${app_paths[@]}"
+	if [[ ! -d "${app_path}" ]]; then
+		die "Not found an app file: ${app_path}"
 	fi
-	validate_app "${app_paths[0]}"
+	validate_app "${app_path}"
 }
 
 if test $# = 0; then
diff --git a/libexec/util b/libexec/util
--- a/libexec/util
+++ b/libexec/util
@@ -1,19 +1,29 @@
 #!/usr/bin/env bash -eu
 # @(#) relax: utility functions
 
-# Util variables
+#################
+###  Defines  ###
+#################
+
 export REL_TEMP_DIR=
-export LOG_LEVEL=
-export LOG_LEVEL_DEBUG=DEBUG
-export LOG_LEVEL_VERBOSE=VERBOSE
+export REL_LOG_LEVEL=
+export REL_LOG_LEVEL_DEBUG=DEBUG
+export REL_LOG_LEVEL_VERBOSE=VERBOSE
 export ARROW="${BLUE}==>${NC}${BOLD}"
 export ERR=${RED}Error:${NC}
 export WARN=${YELLOW}Warning:${NC}
 export NOTE=${BOLD}Note:${NC}
 
-#############
-### Utils ###
-#############
+#################
+### Functions ###
+#################
+
+check_toolchain () {
+	which xcodebuild > /dev/null || die "Not found xcodebuild"
+	which /usr/libexec/PlistBuddy > /dev/null || die "Not found /usr/libexec/PlistBuddy"
+	which plutil > /dev/null || die "Not found plutil"
+	which codesign > /dev/null || die "Not found codesign"
+}
 
 pop_all() {
 	local arr=($(dirs))
@@ -53,10 +63,11 @@ clean_temp () {
 teardown () {
 	pop_all
 	if [ -f $REL_CONFIG ]; then
-		for bak in $(find $HERE -name *.$BAK_EXT)
+		find $HERE -name "*.$BAK_EXT" |\
+		while IFS= read bak
 		do
-			cp $bak ${bak%.$BAK_EXT}
-			rm $bak
+			cp "$bak" "${bak%.$BAK_EXT}"
+			rm "$bak"
 		done
 	fi
 }
@@ -88,7 +99,7 @@ die_with_status () {
 }
 
 ###############
-### Logging ###
+### Logger  ###
 ###############
 
 __log () {
@@ -102,14 +113,14 @@ __log () {
 }
 
 logv () {
-	if [[ ${LOG_LEVEL:-undefined} =~ .*"$LOG_LEVEL_VERBOSE".* ]]; then
+	if [[ ${REL_LOG_LEVEL:-undefined} =~ .*"$REL_LOG_LEVEL_VERBOSE".* ]]; then
 		__log "$@"
 	fi
 }
 
 
 logd () {
-	if [[ ${LOG_LEVEL:-undefined} =~ .*"$LOG_LEVEL_DEBUG".* ]]; then
+	if [[ ${REL_LOG_LEVEL:-undefined} =~ .*"$REL_LOG_LEVEL_DEBUG".* ]]; then
 		__log "$@"
 	fi
 }
@@ -118,6 +129,7 @@ logi () {
 	__log "$@"
 }
 
+declare -x -f check_toolchain
 declare -x -f fin die die_with_status
 declare -x -f logi logv logd __log
 declare -x -f make_temp pop_all clean_temp TRAP
diff --git a/libexec/util-build b/libexec/util-build
--- a/libexec/util-build
+++ b/libexec/util-build
@@ -42,14 +42,11 @@ __map_vals () {
 		sdk=iphoneos
 	fi
 
-	if [ -z $configuration ]; then
-		is_default_configuration=true
-	else
-		is_default_configuration=false
-	fi
-
-	if test -z $scheme; then
+	if [[ -z $release ]]; then
 		die "Undefined '$release' in Relfile"
+	fi
+	if [[ -z $scheme ]]; then
+		die "'scheme' of $release isn't defined in Relfile"
 	fi
 }
 
@@ -75,61 +72,120 @@ __replace_development_team () {
 	done
 }
 
-# load_xcode_build_settings <scheme> [<xcodebuild_options>]
-load_xcode_build_settings () {
-	local scheme=$1
+# get_build_base_params <scheme> [buildsettings=value] ...
+get_build_params_file () {
+	local scheme params xcode_build_params
+	scheme="$1"
 	shift
 
-	if test ! -d $REL_TEMP_DIR; then
-		die "Not found Temporary directory"
+	xcode_build_params=$REL_TEMP_DIR/xcode_build_params
+	rm -rf $xcode_build_params
+
+	if [[ ${REL_CONFIG_workspace-undefined} != "undefined" ]]; then
+		params=( -workspace "$REL_CONFIG_workspace.xcworkspace" )
+	else
+		params=( -project "$REL_CONFIG_xcodeproj.xcodeproj" )
 	fi
 
-	local cmd="xcodebuild -showBuildSettings"
-	if test ! ${REL_CONFIG_workspace-undefined} == "undefined"; then
-		cmd+=" -workspace $REL_CONFIG_workspace.xcworkspace"
-	fi
-
-	cmd+=" -scheme $scheme"
+	params+=(-scheme "${scheme}")
 
 	if test $# -gt 0; then
-		local options=("$@")
-		cmd+=" ${options[@]}"
+		for arg in "$@"
+		do
+			params+=( "$arg" )
+		done
+	fi
+	
+	[[ ${params[@]} =~ "-configuration" ]] || [[ -z $configuration ]] ||\
+		params+=( -configuration "$configuration" )
+
+	[[ -z $provisioning_profile ]] || params+=( PROVISIONING_PROFILE_SPECIFIER="$provisioning_profile" )
+	[[ -z $team_id ]] || param+=( DEVELOPMENT_TEAM="$team_id" )
+
+	params+=( ONLY_ACTIVE_ARCH=NO )
+
+	# Should use development signing for archive. Refer to this session, 
+	# https://developer.apple.com/videos/play/wwdc2016/401/.
+	# But it's not working when exporint ana adhoc IPA file.
+	# I confirmed It's working well in Xcode 7.3.1.
+	params+=( CODE_SIGN_IDENTITY="iPhone Developer" )
+
+	if test "${build_settings:-undefined}" != undefined; then
+		if test ${#build_settings[@]} -gt 0; then
+			for s in "${build_settings[@]}"; do
+				params+=( "${s//\{\}/ }" )
+			done
+		fi
 	fi
 
+	for e in "${params[@]}"
+	do
+		echo "$e" >> $xcode_build_params
+	done
+
+	echo "$xcode_build_params"
+}
+
+
+# FIXME This function doesn't load all xcode build settings.
+# load_xcode_build_settings [<xcode_build_params_file>]
+load_xcode_build_settings () {
 	if test ! -d $REL_TEMP_DIR/xcode-settings; then
 		mkdir -p $REL_TEMP_DIR/xcode-settings;
 	fi
 
-	local xcode_settings_path="$REL_TEMP_DIR/xcode-settings/${cmd// /-}"
+	local params=()
+	if [[ $# = 1 ]]; then
+		while read p
+		do
+			params+=( "$p" )
+		done < $1
+	fi
 
-	logd ${cmd}
+	logd "${params[@]}"
 
-	if ! test -f "$xcode_settings_path"; then
-		cmd+=" 2>/dev/null" # Get ride of 'DeveloperPortal: Using pre-existing current store at URL'
-		cmd+=" | tail -n +2 | sed 's/^ *//' | sed 's/ = /=\"/'| grep -v -e UID -e VERSION_INFO_STRING | sed 's/$/\"/'"
+	local file_name
+	file_name="${params[@]}"
+	file_name="${file_name// /-}"
+	local xcode_settings_file="$REL_TEMP_DIR/xcode-settings/${file_name//\"/}"
+	local export_xcode_settings="$REL_TEMP_DIR/xcode-settings/${file_name//\"/}-export"
 
-		eval "$cmd" | while read line
+	if ! test -f "$xcode_settings_file"; then
+		# Get ride of 'DeveloperPortal: Using pre-existing current store at URL'
+
+		xcodebuild -showBuildSettings "${params[@]}" 2>/dev/null >"$xcode_settings_file"
+
+		cat "$xcode_settings_file" | tail -n +2 | \
+		sed -e "
+		s/^ *//;
+		s/ = /='/;
+		s/$/'/;
+		" | \
+		grep \
+		-e "CONFIGURATION\|INFOPLIST_PATH\|PRODUCT_SETTINGS_PATH"\
+		-e "PRODUCT_BUNDLE_IDENTIFIER\|DEVELOPMENT_TEAM"\
+		-e "FULL_PRODUCT_NAME\|PRODUCT_NAME\|TARGETNAME"\
+		-e "PROJECT_DIR\|PROJECT_FILE_PATH\|PROJECT_NAME"\
+		-e "CODESIGNING_FOLDER_PATH\|TARGET_BUILD_DIR\|BUILT_PRODUCTS_DIR"\
+		-e "OBJROOT\|PUBLIC_HEADERS_FOLDER_PATH" \
+		-e "DWARF_DSYM_FILE_NAME\|DWARF_DSYM_FOLDER_PATH" \
+		-e "CURRENT_PROJECT_VERSION" \
+		| while read line
 		do 
-			if [[ "$line" =~ ^\" ]]; then
-				continue
-			fi
-			if [[ "$line" =~ ^"Build" ]]; then
-				continue
-			fi
-			echo "export $line" >> "$xcode_settings_path"
+			echo "export $line" >> "$export_xcode_settings"
 		done
 	fi
 
-	if ! test -f "$xcode_settings_path"; then
+	if ! test -f "$export_xcode_settings"; then
 		die "load_xcode_build_settings: Could not load the build settings."
 	fi
 
-	if [[ ${LOG_LEVEL:-undefined} =~ .*"$LOG_LEVEL_DEBUG".* ]]; then
-		echo "$xcode_settings_path"
-		cat "$xcode_settings_path"
+	if [[ ${REL_LOG_LEVEL:-undefined} =~ .*"$REL_LOG_LEVEL_DEBUG".* ]]; then
+		echo "$export_xcode_settings"
+		cat "$export_xcode_settings"
 	fi
-	source "$xcode_settings_path"
-	logd "$xcode_settings_path"
+	source "$export_xcode_settings"
+	logd "$export_xcode_settings"
 }
 
 print_xcode_version() {
@@ -149,16 +205,25 @@ print_info_plist () {
 	shift
 	case $command in 
 	version)
-		echo $(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$1")
+		echo $(/usr/libexec/PlistBuddy -c \
+			"Print :CFBundleShortVersionString" "$1" 2>&1\
+			| grep -v "Does Not Exist")
 		;;
+
 	bundle_version) 
-		echo $(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$1")
+		echo $(/usr/libexec/PlistBuddy -c \
+			"Print :CFBundleVersion" "$1" 2>&1\
+			| grep -v "Does Not Exist")
 		;;
 	bundle_identifier)
-		echo $(/usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" "$1" )
+		echo $(/usr/libexec/PlistBuddy -c\
+			"Print :CFBundleIdentifier" "$1" 2>&1\
+			| grep -v "Does Not Exist")
 		;;
 	bundle_identifier_prefix)
-		local app_id=$(/usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" "$1" )
+		local app_id=$(/usr/libexec/PlistBuddy -c\
+			"Print :CFBundleIdentifier" "$1" 2>&1\
+			| grep -v "Does Not Exist")
 		echo "${app_id%.*}"
 		;;
 	*)
@@ -174,17 +239,22 @@ teardown_build () {
 			cp "$INFO_PLIST_PATH".$BAK_EXT "$INFO_PLIST_PATH"
 		fi
 	fi
-	if [[ -f $REL_CONFIG_xcodeproj.xcodeproj/project.pbxproj.$BAK_EXT ]]; then
-		rm $REL_CONFIG_xcodeproj.xcodeproj/*.$BAK_EXT
-	fi
-	if [[ -f $REL_CONFIG_xcodeproj.xcodeproj/project.pbxproj.org ]]; then
-		mv $REL_CONFIG_xcodeproj.xcodeproj/project.pbxproj.org $REL_CONFIG_xcodeproj.xcodeproj/project.pbxproj
+	if [[ ${PROJECT_FILE_PATH:-undefined} != undefined ]]; then
+		if [[ -f "$PROJECT_FILE_PATH"/project.pbxproj.$BAK_EXT ]]; then
+			rm "$PROJECT_FILE_PATH"/*.$BAK_EXT
+		fi
+		if [[ -f "$PROJECT_FILE_PATH"/project.pbxproj.org ]]; then
+			mv "$PROJECT_FILE_PATH"/project.pbxproj.org "$PROJECT_FILE_PATH"/project.pbxproj
+		fi
 	fi
 }
 
 # prepare_build <release>
 setup_build () {
-	cp -a $REL_CONFIG_xcodeproj.xcodeproj/project.pbxproj $REL_CONFIG_xcodeproj.xcodeproj/project.pbxproj.org
+	if test ! -d $REL_TEMP_DIR; then
+		die "Not found Temporary directory"
+	fi
+	local release _params
 
 	local release="$1"
 
@@ -192,18 +262,22 @@ setup_build () {
 
 	__check_scheme "$scheme"
 
+	params_file=$(get_build_params_file "$scheme")
+
+	load_xcode_build_settings $params_file
+
+	if [ ${FULL_PRODUCT_NAME:-undefined} = undefined ]; then
+		die "This scheme($scheme) isn't for an Application, Framework or Library target"
+	fi
+
+	cp -a "$PROJECT_FILE_PATH"/project.pbxproj "$PROJECT_FILE_PATH"/project.pbxproj.org
+
 	## Replace TEAMID if needed
 	if test "${team_id:-undefined}" != undefined; then
 		__replace_development_team $team_id
 	fi
 
-	if [ -z $configuration ]; then
-		load_xcode_build_settings $scheme -sdk "$sdk"
-	else
-		load_xcode_build_settings $scheme -configuration "$configuration" -sdk "$sdk"
-	fi
-
-	logi "$ARROW Setting up build configurations"
+	logi "$ARROW Set up '$release' configurations"
 	logi "Configuration: $CONFIGURATION"
 	configuration=$CONFIGURATION
 
@@ -211,8 +285,9 @@ setup_build () {
 
 	# StaticLibrary doesn't have a Info.plist
 	if [ -z $INFO_PLIST_PATH ]; then
-		PRODUCT_BUILD_ROOT=$REL_RELEASE_ROOT/$release
+		PRODUCT_BUILD_ROOT="$REL_RELEASE_ROOT/$release/$scheme"
 		logi "Build Root: $PRODUCT_BUILD_ROOT"
+		mkdir -p "$PRODUCT_BUILD_ROOT"
 		return
 	fi
 
@@ -220,47 +295,55 @@ setup_build () {
 	logd "Info plist: $INFO_PLIST_PATH"
 
 	## Team ID
-	if test ${DEVELOPMENT_TEAM:-undefined} = undefined; then
-		die "Please update your project file with Xcode 8.0+"
+	if test ${DEVELOPMENT_TEAM:-undefined} != undefined; then
+		logi "Team ID: $DEVELOPMENT_TEAM"
 	fi
-	logi "Team ID: $DEVELOPMENT_TEAM"
 
 	## Bundle Identifier
 	if [[ "${bundle_identifier:-undefined}" != undefined ]]; then
 		sed -i .$BAK_EXT \
 		-e "s/\(PRODUCT_BUNDLE_IDENTIFIER = \)\($PRODUCT_BUNDLE_IDENTIFIER\);/\1$bundle_identifier;/" \
-		$REL_CONFIG_xcodeproj.xcodeproj/project.pbxproj
+		"$PROJECT_FILE_PATH"/project.pbxproj
+		/usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $bundle_identifier" "$INFO_PLIST_PATH"
+		PRODUCT_BUNDLE_IDENTIFIER=$bundle_identifier
+	fi
+
+	## Support a xcode project file not including PRODUCT_BUNDLE_IDENTIFIER 
+	if test ${PRODUCT_BUNDLE_IDENTIFIER:-undefined} = undefined; then
+		PRODUCT_BUNDLE_IDENTIFIER="$(print_info_plist bundle_identifier $INFO_PLIST_PATH)"
+		if [[ $PRODUCT_BUNDLE_IDENTIFIER =~ (.*)\${PRODUCT_NAME:rfc1034identifier}(.*) ]]; then
+			PRODUCT_BUNDLE_IDENTIFIER="$(eval echo ${BASH_REMATCH[1]}$PRODUCT_NAME)"
+			if [[ ! -z ${BASH_REMATCH[2]} ]]; then
+				PRODUCT_BUNDLE_IDENTIFIER+="${BASH_REMATCH[2]}"
+			fi
+		fi
 	else # PRODUCT_BUNDLE_IDENTIFIER sometimes can be differenct from Info.plist
-		# Should eval a CFBundleIdentifier value because it's can be $(PRODUCT_BUNDLE_IDENTIFIER)
+
 		local info_plist_bundle_identifier=$(print_info_plist bundle_identifier "$INFO_PLIST_PATH")
-		if [[ "$info_plist_bundle_identifier" != "\$(PRODUCT_BUNDLE_IDENTIFIER)" ]]; then
-			if [[ $PRODUCT_BUNDLE_IDENTIFIER != "$info_plist_bundle_identifier" ]]; then
+
+		# Should eval a CFBundleIdentifier value because it's can be $(PRODUCT_BUNDLE_IDENTIFIER)
+		if [[ "$info_plist_bundle_identifier" = "\$(PRODUCT_BUNDLE_IDENTIFIER)" ]]; then
+			:
+		else
+			if [[ ${PRODUCT_BUNDLE_IDENTIFIER} != "$info_plist_bundle_identifier" ]]; then
 				logi "$ERR PRODUCT_BUNDLE_IDENTIFIER($PRODUCT_BUNDLE_IDENTIFIER) setting is different from the value($info_plist_bundle_identifier) of CFBundleIdentifier in Info.plist."
 				die "$NOTE Please edit 'Product Bundle Identifier' in '$PRODUCT_NAME' > 'Build Settings' pane."
 			fi
+
+			PRODUCT_BUNDLE_IDENTIFIER=$info_plist_bundle_identifier
 		fi
 	fi
 
+	logi "Bundle Identifier: $PRODUCT_BUNDLE_IDENTIFIER"
+
+	## Provisioning Profile
 	if [[ -n $provisioning_profile ]]; then
 		logi "$ARROW Change ProvisioningStyle to Manual for \"$provisioning_profile\""
 		# Custom Sigining
 		sed -i .$BAK_EXT \
 		-e "/DevelopmentTeam/d; s/\(ProvisioningStyle = \)Automatic/\1Manual/" \
-		$REL_CONFIG_xcodeproj.xcodeproj/project.pbxproj 
+		"$PROJECT_FILE_PATH"/project.pbxproj 
 	fi
-
-	# Support a project file not defining PRODUCT_BUNDLE_IDENTIFIER 
-	if test ${PRODUCT_BUNDLE_IDENTIFIER:-undefined} = undefined; then
-		PRODUCT_BUNDLE_IDENTIFIER="$(print_info_plist bundle_identifier $INFO_PLIST_PATH)"
-		if [[ $PRODUCT_BUNDLE_IDENTIFIER =~ (.*)\${PRODUCT_NAME:rfc1034identifier}(.*) ]]; then
-			PRODUCT_BUNDLE_IDENTIFIER="$(eval echo ${BASH_REMATCH[1]}$PRODUCT_NAME)"
-			if test ! -z ${BASH_REMATCH[2]}; then
-				PRODUCT_BUNDLE_IDENTIFIER+="${BASH_REMATCH[2]}"
-			fi
-		fi
-	fi
-
-	logi "Bundle Identifier: $PRODUCT_BUNDLE_IDENTIFIER"
 
 	## Bundle Version
 	if test "${bundle_version_format:-undefined}" = undefined; then
@@ -284,20 +367,24 @@ setup_build () {
 			gsub(/%B/, "'"${branch//\//_}"'");
 			print
 		}') # See [Semantic Versioning 2.0.0](http://semver.org)
+		/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUNDLE_VERSION" "$INFO_PLIST_PATH"
 	fi
+	logi "Bundle Version: $BUNDLE_VERSION"
+
+	## Product Build Root
 	if [ -z $BUNDLE_VERSION ]; then
-		PRODUCT_BUILD_ROOT=$REL_RELEASE_ROOT/$release/$scheme
+		PRODUCT_BUILD_ROOT="$REL_RELEASE_ROOT/$release/$scheme"
 	else
 		if [[ $BUNDLE_VERSION =~ (.*)\$\(CURRENT_PROJECT_VERSION\)(.*) ]]; then
 			BUNDLE_VERSION="${BASH_REMATCH[1]}${CURRENT_PROJECT_VERSION}${BASH_REMATCH[2]}"
 		fi
-		logi "Bundle Version: $BUNDLE_VERSION"
 		if [[ ! $BUNDLE_VERSION =~ "$configuration" ]]; then
 			BUNDLE_VERSION=$BUNDLE_VERSION-$configuration
 		fi
 		PRODUCT_BUILD_ROOT=$(eval echo "$REL_RELEASE_ROOT/$release/$scheme-$BUNDLE_VERSION")
 	fi
 	logi "Build Root: $PRODUCT_BUILD_ROOT"
+	mkdir -p "$PRODUCT_BUILD_ROOT"
 }
 
 
@@ -320,7 +407,7 @@ update_archived_entitlements_xcent () {
 	#codesign -dv "${app_path}" 2>&1 | grep -e "Format\|Identifier\|Signed Time" > $REL_TEMP_DIR/codesign_info
 	#local cs_team_id=$(cat $REL_TEMP_DIR/codesign_info | sed -ne "s/TeamIdentifier=\(.*\)/\1/p")
 
-	local app_id=$(/usr/libexec/PlistBuddy -c "Print :application-identifier" $app_path/$ARCHIVED_ENTITLEMENTS_XCENT)
+	local app_id=$(/usr/libexec/PlistBuddy -c "Print :application-identifier" "$app_path/$ARCHIVED_ENTITLEMENTS_XCENT")
 	_src_team=${app_id%%.*}
 
 	cp "$app_path/$ARCHIVED_ENTITLEMENTS_XCENT" "$_entitlements_xcent"
@@ -339,11 +426,11 @@ update_archived_entitlements_xcent () {
 	logv "$ARROW Updated $ARCHIVED_ENTITLEMENTS_XCENT(TeamID: $_dest_team)"
 	cat $_entitlements_xcent | logv
 
-	cp "$_entitlements_xcent" "$app_path"/$ARCHIVED_ENTITLEMENTS_XCENT
+	cp "$_entitlements_xcent" "$app_path/$ARCHIVED_ENTITLEMENTS_XCENT"
 }
 
 declare -x -f __check_scheme __map_vals __replace_development_team
-declare -x -f load_xcode_build_settings
+declare -x -f load_xcode_build_settings get_build_params_file
 declare -x -f print_info_plist print_xcode_version
 declare -x -f setup_build teardown_build
 declare -x -f update_archived_entitlements_xcent
