build: output an universal dSYM bundle

diff --git a/libexec/relax-build b/libexec/relax-build
--- a/libexec/relax-build
+++ b/libexec/relax-build
@@ -39,7 +39,8 @@ build_project () {
 		else
 			params=( -project "$REL_CONFIG_xcodeproj.xcodeproj" )
 		fi
-		params+=( -scheme "${scheme}" -sdk "$sdk" -configuration "$configuration" -derivedDataPath "$REL_TEMP_DIR/$Distribution" )
+		params+=( -scheme "${scheme}" -sdk "$sdk" -configuration "$configuration")
+		params+=( -derivedDataPath "$REL_TEMP_DIR/$Distribution" )
 		params+=(
 			ONLY_ACTIVE_ARCH=NO \
 			CODE_SIGN_IDENTITY= \
@@ -91,20 +92,23 @@ build_project () {
 		fi
 	fi
 
-	local product_path=$REL_TEMP_DIR/$Distribution/Build/Products/$configuration-$sdk/$FULL_PRODUCT_NAME
-	logv "Built Product: $product_path"
+	local product_root="$REL_TEMP_DIR/$Distribution/Build/Products/$configuration-$sdk"
 
 	# Save the built product
 	mkdir "$PRODUCT_BUILD_ROOT"/$configuration-$sdk
-	cp -a "$product_path" "$PRODUCT_BUILD_ROOT"/$configuration-$sdk/
-	local dSYM="$BUILD_DIR/$configuration-$sdk/$DWARF_DSYM_FILE_NAME"
-	[ -d $dSYM ] && cp -a "$dSYM" "$PRODUCT_BUILD_ROOT"/$configuration-$sdk/
 
-	# Use a saved built output because Xcode 10 can clear `$product_path` artifact on the next build
-	local odir="$REL_TEMP_DIR/build/$configuration-$sdk"
-	mkdir -p "$odir"
-	mv "$product_path" "$odir"/
-	Output="$odir/$FULL_PRODUCT_NAME"
+	local product_path="$product_root/$FULL_PRODUCT_NAME"
+	cp -a "$product_path" "$PRODUCT_BUILD_ROOT"/$configuration-$sdk/
+
+	Output="$PRODUCT_BUILD_ROOT/$configuration-$sdk/$FULL_PRODUCT_NAME"
+	logv "Built Product: $Output"
+
+	local dsym_path="$product_root/$DWARF_DSYM_FILE_NAME"
+	if [ -d $dsym_path ]; then
+		cp -a "$dsym_path" "$PRODUCT_BUILD_ROOT"/$configuration-$sdk/
+		OutputDSYM="$PRODUCT_BUILD_ROOT/$configuration-$sdk/$DWARF_DSYM_FILE_NAME"
+		logv "Built Product(dSYM): $OutputDSYM"
+	fi
 }
 
 merge_frameworks() {
@@ -121,10 +125,66 @@ merge_frameworks() {
 
 	cp -a "$fw_iphoneos"  "$fw_dest"
 
-	lipo -create -output "${fw_dest}/${target}" "${fw_iphoneos}/${target}" "${fw_iphonesimulator}/${target}"
+	lipo -create \
+		-output "${fw_dest}/${target}" \
+		"${fw_iphoneos}/${target}" \
+		"${fw_iphonesimulator}/${target}"
 
 	if [ -d "${fw_iphonesimulator}/Modules/${target}.swiftmodule" ]; then
-		cp -nR "${fw_iphonesimulator}/Modules/${target}.swiftmodule/" "${fw_dest}/Modules/${target}.swiftmodule/"
+		cp -nR "${fw_iphonesimulator}/Modules/${target}.swiftmodule/" \
+			"${fw_dest}/Modules/${target}.swiftmodule/"
+	fi
+}
+
+copy_framework() {
+	local source="$1"
+	local dest
+
+	if [[ -d "$source" ]]; then
+		dest="${HERE}/${Framework_name}.framework"
+
+		rm -rf "$dest"
+		rm -rf "$dest".zip
+
+		ditto "${source}" "$dest"
+		logi "./${Framework_name}.framework"
+		ditto -c -k --sequesterRsrc --keepParent "$source" "$dest".zip
+		logi "./${Framework_name}.framework.zip"
+	fi
+}
+
+merge_dSYMs() {
+	[ $# == 4 ] || die "Invalid argument"
+
+	local target=$1
+	local dsym_iphoneos=$2
+	local dsym_iphonesim=$3
+	local dest=$4
+
+	[ ! -d "$dest" ] || rm -rf $dest
+
+	logi "$ARROW Creating a universal dSYM..."
+
+	cp -a "$dsym_iphoneos"  "$dest"
+
+	lipo -create \
+		-output "${dest}/Contents/Resources/DWARF/${target}" \
+		"${dsym_iphoneos}/Contents/Resources/DWARF/${target}" \
+		"${dsym_iphonesim}/Contents/Resources/DWARF/${target}"
+}
+
+copy_dsym() {
+	local source="$1"
+	if [[ -d "$source" ]]; then
+		dest="${HERE}/${Framework_name}.framework.dSYM"
+
+		rm -rf "$dest"
+		rm -rf "$dest".zip
+
+		ditto "${source}" "$dest"
+		logi "./${Framework_name}.framework.dSYM"
+		ditto -c -k --sequesterRsrc --keepParent "$source" "$dest".zip
+		logi "./${Framework_name}.framework.dSYM.zip"
 	fi
 }
 
@@ -142,39 +202,40 @@ build_framework() {
 
 	local current_sdk sdk_platform other_platform sdk_version
 	local build_project other_built_product
+	local os_fw sim_fw
+	local os_dsym sim_dsym
 
 	logi "$ARROW Generate $TARGETNAME Framework ($configuration)"
 
 	local name=${TARGETNAME}
 	local framework_location="${PRODUCT_BUILD_ROOT}/${name}.framework"
+	local dsym_location="${PRODUCT_BUILD_ROOT}/${name}.framework.dSYM"
 
 	build_project "$scheme" "iphoneos" "$configuration"
 	# Save the build output because Xcode 10 can clear it on the next build
-	local os_fw="$Output"
+	os_fw="$Output"
+	os_dsym="$OutputDSYM"
 
 	if [[ $No_simulator == false ]]; then
 		build_project "$scheme" "iphonesimulator" "$configuration"
-		local sim_fw="$Output"
+		sim_fw="$Output"
+		sim_dsym="$OutputDSYM"
 		merge_frameworks "$name" "$os_fw" "$sim_fw" "$framework_location"
 	else
 		cp -a "$os_fw" "$framework_location"
 	fi
+	# Copy framework to the current workspace
+	copy_framework "${framework_location}"
 
-	dest="${HERE}/${name}.framework"
-	rm -rf "$dest"
+	[[ $os_dsym ]] || return
 
-	# 6 - Copy the framework to the current workspace
-	ditto "${framework_location}" "$dest"
-
-	logi "$ARROW Framework: ./${name}.framework"
-
-	if [[ -d "$framework_location" ]];
-	then
-		ditto -c -k --sequesterRsrc --keepParent "$framework_location" "$dest".zip
-		logi "zip: ./${name}.framework.zip"
+	# Copy dSYM to the current workspace
+	if [[ $No_simulator == false ]]; then
+		merge_dSYMs "$name" "$os_dsym" "$sim_dsym" "${dsym_location}"
 	else
-		die "Cound not find any zipping framework: ${framework_location}"
+		cp -a "$os_dsym" "$dsym_location"
 	fi
+	copy_dsym "${dsym_location}"
 }
 
 # make_framework <iphoneos-product-path> <iphonesimulator-product-path> <location>
@@ -263,21 +324,8 @@ build_framework_with_static () {
 		fi
 	done < <(find "$HERE" -name module.modulemap)
 
-	dest="${HERE}/${Framework_name}.framework"
-	rm -rf "$dest"
-
-	# 6 - Copy the framework to the current workspace
-	ditto "${framework_location}" "$dest"
-
-	logi "$ARROW ./${Framework_name}.framework"
-
-	if [[ -d "$framework_location" ]];
-	then
-		ditto -c -k --sequesterRsrc --keepParent "$framework_location" "$dest".zip
-		logi "zip: ./${Framework_name}.framework.zip"
-	else
-		die "Cound not find any zipping framework: ${framework_location}"
-	fi
+	# Copy framework to the current workspace
+	copy_framework "${framework_location}"
 }
 
 Build_cmd_semaphore=
@@ -288,6 +336,7 @@ Show_progress=false
 Distribution=
 Configuration=
 Output=
+OutputDSYM=
 
 while [ $# -ne 0 ];  do
 	arg=$1
