util: Add kill_childprocesses()

diff --git a/libexec/util b/libexec/util
--- a/libexec/util
+++ b/libexec/util
@@ -42,12 +42,19 @@ check_toolchain () {
 	which security > /dev/null || die "Not found security"
 }
 
+kill_childprocesses () {
+	local cpids=$(jobs -p)
+	if [[ -n $cpids ]]; then
+		kill $cpids
+	fi
+}
+
 TRAP() {
 	local cmd=$1
-	trap "${cmd}" EXIT
-	trap "${cmd} die \"Interrupted\"" INT HUP
-	trap "${cmd} die \"Aborted \"" ABRT
-	trap "${cmd} die \"Terminate\"" TERM
+	trap "${cmd} kill_childprocesses;" EXIT
+	trap "${cmd} kill_childprocesses; die \"Interrupted\"" INT HUP
+	trap "${cmd} kill_childprocesses; die \"Aborted \"" ABRT
+	trap "${cmd} kill_childprocesses; die \"Terminate\"" TERM
 }
 	
 
@@ -147,4 +154,4 @@ declare -x -f check_toolchain compare_versions
 declare -x -f fin die die_with_status
 declare -x -f logi logv logd __log
 declare -x -f make_temp clean_temp 
-declare -x -f teardown TRAP
+declare -x -f teardown TRAP kill_childprocesses
